name: Publish Companion App to DockerHub

on:
  push:
    tags:
      - "v*.*.*"
    branches-ignore:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta BB Static
        id: meta_static
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/budgetbutlerweb-companion-static
      -
        name: Docker meta BB Companion
        id: meta_companion
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/budgetbutlerweb-companion-fpm
      -
        name: Docker meta BB Offline
        id: meta_offline
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/budgetbutlerweb-offline
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -       
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -     
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - 
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push static
        id: docker_build_bb_static
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.static
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/budgetbutlerweb-companion-frontend-static:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      -
        name: Build and push api
        id: docker_build_bb_api
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.api
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/budgetbutlerweb-companion-api:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      -
        name: Build and push cron
        id: docker_build_bb_cron
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.cron
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/budgetbutlerweb-companion-cron:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      -
        name: Build and push desktop app
        id: docker_build_bb_desktopapp
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.desktopapp
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/budgetbutlerweb-desktopapp:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      -
        name: Build and push offline
        id: docker_build_bb_offline
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.offline
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta_offline.outputs.tags }}
          labels: ${{ steps.meta_offline.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
